### ISSUE TITLE
It seems impossible to limit a running docker container's memory......

### ISSUE THREAD

**Issue by xiechengsheng** [yncxcw/MRDocker#1]
Dear Wei, sorry to interrupt you again. I know the main idea of this paper is that the node's task manager reallocates different docker containers's memory in one node. But on my server(CentOS 7.2 and docker version 1.12), a running docker's usable memory can't be updated when this docker runs out of the memory resource that node's task manager allocates to it; For example, when the node's task manager allocates 100MB memory to one docker, and this running docker actually uses 100MB memory. And if I try to use system memory's cgroups to limit this running docker's usable memory to 50MB, this operation always fails. Is this normal? and what docker version do you use? Thanks for your codes and looking forward to your reply~

**Comment by yncxcw** [comment]
hi, xiecheng,

You need to first limit the running tasks' CPU to a minimum level e.g., 1% 

You can use this command for updating.
docker update --cpu-quota 1000 container1
Then limit the memory, by using:
docker update -m m --memory-swap ms container1 (ms > m)

Since it takes time to swap memory to disk, please try not swap more than 200M memory for HDD. I tried it works fine for swapping 1GB on SSD in 2 seconds. 

Otherwise, since your process in container continuously touches the memory, it will report "resource busy" error,  if CPU is not limited.

Feel free to ask me more questions if you need some help!

Wei

**Comment by xiechengsheng** [comment]
Cool, it really works on my server! Thanks! :satisfied:
